import { ReactComponent as ArrowDown } from './arrow-circle-down.svg'
import { ReactComponent as ArrowLeft } from './arrow-circle-left.svg'
import { ReactComponent as ArrowRight } from './arrow-circle-right.svg'
import { ReactComponent as Checkmark } from './checkmark.svg'
import { ReactComponent as Pause } from './pause.svg'
import { ReactComponent as Clock } from './clock.svg'
import { ReactComponent as Person } from './person.svg'
import { ReactComponent as People } from './people.svg'
import { ReactComponent as Plus } from './plus-circle.svg'
import { ReactComponent as Minus } from './minus-circle.svg'
export { ArrowDown, ArrowLeft, ArrowRight, Checkmark, Pause, Clock, Person, People, Plus, Minus }
